name: app tests

run-name: ${{ github.actor }} 

on: 
    push:
      branches: [main, master]
    pull_request:
      branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv shell --fancy --python $(which python)
          pipenv install -r requirements.txt 
          
        working-directory: web-app

      - name: Run tests
        run: |
          pipenv run pytest --cov=app tests/test_app.py
        working-directory: web-app